"""empty message

Revision ID: b6048c860b2e
Revises: a305fedc541c
Create Date: 2022-02-08 11:53:34.063115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b6048c860b2e"
down_revision = "a305fedc541c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "publisher", sa.Column("last_published", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("publisher", "last_published")
    # ### end Alembic commands ###
