"""empty message

Revision ID: c93d17410aaa
Revises: 3ab75b91821d
Create Date: 2021-11-29 16:18:46.126300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c93d17410aaa"
down_revision = "3ab75b91821d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dataset_stats_dataset"), "dataset_stats", ["dataset"], unique=False
    )
    op.create_index(
        op.f("ix_dataset_stats_name"), "dataset_stats", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_dataset_stats_value"), "dataset_stats", ["value"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dataset_stats_value"), table_name="dataset_stats")
    op.drop_index(op.f("ix_dataset_stats_name"), table_name="dataset_stats")
    op.drop_index(op.f("ix_dataset_stats_dataset"), table_name="dataset_stats")
    op.drop_table("dataset_stats")
    # ### end Alembic commands ###
